package com.intellimeds.ai;

import com.intellimeds.ai.dto.*;
import com.intellimeds.ai.model.AiHistory;
import com.intellimeds.ai.model.AiProvider;
import com.intellimeds.ai.repository.AiHistoryRepository;
import com.intellimeds.ai.repository.AiProviderRepository;
import com.intellimeds.exception.ResourceNotFoundException;
import com.intellimeds.model.User;
import com.intellimeds.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class AiService {

    private final AiProviderRepository providerRepository;
    private final AiHistoryRepository historyRepository;
    private final UserRepository userRepository;

    public List<AiProviderResponse> getProviders() {
        return providerRepository.findAll().stream()
                .map(this::mapToProviderResponse)
                .collect(Collectors.toList());
    }

    @Transactional
    public AiProviderResponse updateProvider(UpdateProviderRequest request) {
        AiProvider.ProviderType providerType = AiProvider.ProviderType.valueOf(
                request.getProviderType().toUpperCase());

        providerRepository.findByIsSelectedTrue().ifPresent(p -> {
            p.setIsSelected(false);
            providerRepository.save(p);
        });

        AiProvider provider = providerRepository.findByProviderType(providerType)
                .orElseThrow(() -> new ResourceNotFoundException("AI Provider", "type", request.getProviderType()));

        provider.setIsSelected(true);
        providerRepository.save(provider);

        return mapToProviderResponse(provider);
    }

    @Transactional
    public AiExplainResponse explain(AiExplainRequest request, UUID userId) {
        String explanation = generateExplanation(request.getContent());
        String recommendation = generateRecommendation(request.getContent());
        String warnings = generateWarnings(request.getContent());

        AiProvider selectedProvider = providerRepository.findByIsSelectedTrue().orElse(null);

        AiHistory history = AiHistory.builder()
                .user(userId != null ? userRepository.findById(userId).orElse(null) : null)
                .prompt(request.getContent())
                .response(explanation)
                .provider(selectedProvider != null ? selectedProvider.getName() : "OFFLINE")
                .requestType("EXPLAIN")
                .build();
        historyRepository.save(history);

        return AiExplainResponse.builder()
                .explanation(explanation)
                .recommendation(recommendation)
                .warnings(warnings)
                .build();
    }

    public List<AiHistoryResponse> getAiHistory(UUID userId) {
        return historyRepository.findByUserIdOrderByCreatedAtDesc(userId).stream()
                .map(this::mapToHistoryResponse)
                .collect(Collectors.toList());
    }

    @Transactional
    public void deleteAiHistory(UUID historyId) {
        if (!historyRepository.existsById(historyId)) {
            throw new ResourceNotFoundException("AI History", "id", historyId);
        }
        historyRepository.deleteById(historyId);
    }

    private String generateExplanation(String content) {
        return "Based on the provided information: " + content +
               "\n\nThis is a simplified explanation generated by the AI system. " +
               "Please consult a healthcare professional for personalized advice.";
    }

    private String generateRecommendation(String content) {
        return "Recommendation: Continue monitoring and consult your healthcare provider if symptoms persist.";
    }

    private String generateWarnings(String content) {
        return "Warning: This information is for educational purposes only. " +
               "Always seek professional medical advice.";
    }

    private AiProviderResponse mapToProviderResponse(AiProvider provider) {
        return AiProviderResponse.builder()
                .id(provider.getId())
                .name(provider.getName())
                .providerType(provider.getProviderType().name())
                .isActive(provider.getIsActive())
                .isSelected(provider.getIsSelected())
                .build();
    }

    private AiHistoryResponse mapToHistoryResponse(AiHistory history) {
        return AiHistoryResponse.builder()
                .id(history.getId())
                .prompt(history.getPrompt())
                .response(history.getResponse())
                .provider(history.getProvider())
                .requestType(history.getRequestType())
                .createdAt(history.getCreatedAt())
                .build();
    }
}
